# Generated by Django 4.2.3 on 2023-07-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='noimage.png', null=True, upload_to='ProductImages/'),
        ),
    ]
